# Generated by Django 5.1.7 on 2025-03-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du stade', max_length=255)),
                ('location', models.CharField(help_text='Emplacement du stade', max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Capacité du stade')),
                ('description', models.TextField(help_text='Description détaillée du stade')),
                ('image', models.ImageField(blank=True, help_text='Image du stade', null=True, upload_to='stadium_info/')),
                ('facilities', models.TextField(blank=True, help_text='Liste des installations disponibles au stade (ex. parking, restauration, sanitaires, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'information")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dernière mise à jour')),
            ],
        ),
    ]
